### ISSUE TITLE
Suggestions at room's event editor are broken (a box with invisible items inside).

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [ct-js/ct-js#195]
Somehow got introduced in v1.3.

Steps to reproduce:

1. Create a new room;
2. Edit its events;
3. Write `this.`
4. See an empty box of autocompletions that are transparent (?).

It is either an outdated css of monaco, or monaco issue as is, or spmething at rooms' stylesheets.

**Comment by DekosAnjo** [comment]
![Screenshot_20200613_004527](https://user-images.githubusercontent.com/10676754/84559242-48758f00-ad0f-11ea-8292-4267fe0b4872.png)
Same here, really annoying.

**Comment by CosmoMyzrailGorynych** [comment]
A little clue: disabling `overflow: hidden` here brings the suggestions back.

![2020-06-17_17-46](https://user-images.githubusercontent.com/3174357/84860123-951bea00-b0c2-11ea-948b-53f33d6a1f34.png)
