### ISSUE TITLE
Launch Game Errors (not a critical bugs)

### ISSUE THREAD

**Issue by ReptiIe** [ct-js/ct-js#35]
### LAUNCH GAME ERROR 1 

**Describe the bug**
When I am in the Patrons section (Main menu -> Open some project -> Heart icon)
I will click LAUNCH button, to test play.

My project has some errors (it is a empty project, so no wonder),
but errors are not the case here

Issue is that this window with ERRORs for launching project, is "behind" Patrons section.
and even the "X" button to close the errors windo is behind it, but still visible enough. 

**To Reproduce**
1. Make a new project
2. Go to Patrons (heart icon)
3. Click LAUNCH icon (play icon) for test play

**Expected behavior**
Well it would be good if... this "error window" would pop in front of the Patrons section,
if not then maybe go to its own sections or something like that?

**System information report**
Open the hamburger menu at the top-left corner and click "Copy system information" in the "Troubleshooting" section. Paste the copied report here.

**Screenshots (recommended)**
If you look carefully you can see only the "X" from the error window, and it is "behind" the patron section.
![image](https://github.com/user-attachments/assets/efba40ce-14b1-42ec-9c8d-a0029b29cb09)

**Example project (strongly recommended)**
I will skip this, since the reproduction is an easy step.

**Comment by ReptiIe** [comment]
### LAUNCH GAME ERROR 2

This one is a bit tricky, but again open new project,
lets go to ctjs main MENU, and choose **Open CSS style book**

Now I notice 2 things.

1) Open CSS style book will not load, by itself. It freeze(?), loads(?) not sure what it does...
It is simply blank, does not load. But when I click other tab (example ASSETS) and then go back to the main menu,
the Open CSS style book is open! And I can look at it. Great.

2) Once the Open CSS style book is open (does not matter if we "see it" or not),
when we are in Open CSS style book, and we will click LAUNCH, 
the ctjs will... ... not launch the game.

It shows icon of "loading" but it will never load anything.

If I exit the Open CSS style book, it will still "keep on loading" and I can not load the game anymore.
Launch button will not work anymore.

Solution for this is to restart ct.js (whatever you are doing - just save, and exit, and open app again).
Saving, and editing still works at this state.

Is it critical error? Not sure, but just make sure I will let you know about it.

**Comment by CosmoMyzrailGorynych** [comment]
lol

**Comment by CosmoMyzrailGorynych** [comment]
Actually I'm closing this issue because games in ct.js v6 will open in separate windows, so these issues will never happen there.
